---
title: Dr Feng's Coding Club
baseurl: "/"
permalink: "/:title/"
palette: blue
header:
  title: Dr Feng's Coding Club
  logo_img: "/images/feng.png"
  has_nav: true
  menu:
    actions:
    - label: Sign Up
      url: "/signup"
footer:
  logo_img: "/images/feng.png"
  tagline: Dr Feng's Coding Club
  has_nav: true
  nav_title: The Club
  has_social: true
  social_title: Courses
  has_subscribe: true
  subscribe_title: Subscribe
  subscribe_content: Stay up to date with our latest developments.
  content: "&copy; Dr Feng's Coding Club. All rights reserved."
  links: []
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
- jekyll-menus
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- ssg-build.sh
- LICENSE.md
- README.md
- netlify.toml
- stackbit-build.sh
- stackbit-pull.js
collections:
  posts:
    permalink: "/posts/:title/"
